/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsAgentsRouteImport } from './routes/_app/settings/agents'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppRepositoriesRepositoryIdIndexRouteImport } from './routes/_app/repositories/$repositoryId/index'
import { Route as AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRouteImport } from './routes/_app/repositories/$repositoryId/workspaces/$workspaceId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAgentsRoute = AppSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppRepositoriesRepositoryIdIndexRoute =
  AppRepositoriesRepositoryIdIndexRouteImport.update({
    id: '/repositories/$repositoryId/',
    path: '/repositories/$repositoryId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute =
  AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/repositories/$repositoryId/workspaces/$workspaceId',
    path: '/repositories/$repositoryId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/repositories/$repositoryId/': typeof AppRepositoriesRepositoryIdIndexRoute
  '/repositories/$repositoryId/workspaces/$workspaceId': typeof AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings': typeof AppSettingsIndexRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdIndexRoute
  '/repositories/$repositoryId/workspaces/$workspaceId': typeof AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/agents': typeof AppSettingsAgentsRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/repositories/$repositoryId/': typeof AppRepositoriesRepositoryIdIndexRoute
  '/_app/repositories/$repositoryId/workspaces/$workspaceId': typeof AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings/'
    | '/repositories/$repositoryId/'
    | '/repositories/$repositoryId/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/appearance'
    | '/settings'
    | '/repositories/$repositoryId'
    | '/repositories/$repositoryId/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-up'
    | '/_app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/agents'
    | '/_app/settings/appearance'
    | '/_app/settings/'
    | '/_app/repositories/$repositoryId/'
    | '/_app/repositories/$repositoryId/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/agents': {
      id: '/_app/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AppSettingsAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/repositories/$repositoryId/': {
      id: '/_app/repositories/$repositoryId/'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId/'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$repositoryId/workspaces/$workspaceId': {
      id: '/_app/repositories/$repositoryId/workspaces/$workspaceId'
      path: '/repositories/$repositoryId/workspaces/$workspaceId'
      fullPath: '/repositories/$repositoryId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAgentsRoute: typeof AppSettingsAgentsRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAgentsRoute: AppSettingsAgentsRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRepositoriesRepositoryIdIndexRoute: typeof AppRepositoriesRepositoryIdIndexRoute
  AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute: typeof AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRepositoriesRepositoryIdIndexRoute: AppRepositoriesRepositoryIdIndexRoute,
  AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute:
    AppRepositoriesRepositoryIdWorkspacesWorkspaceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
