/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppWorkspacesWorkspaceIdIndexRouteImport } from './routes/_app/workspaces/$workspaceId/index'
import { Route as AppWorkspacesWorkspaceIdTasksTaskIdRouteImport } from './routes/_app/workspaces/$workspaceId/tasks/$taskId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AppWorkspacesWorkspaceIdIndexRoute =
  AppWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspacesWorkspaceIdTasksTaskIdRoute =
  AppWorkspacesWorkspaceIdTasksTaskIdRouteImport.update({
    id: '/workspaces/$workspaceId/tasks/$taskId',
    path: '/workspaces/$workspaceId/tasks/$taskId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof AppWorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/': typeof AppIndexRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/tasks/$taskId': typeof AppWorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdIndexRoute
  '/_app/workspaces/$workspaceId/tasks/$taskId': typeof AppWorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/tasks/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-up'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_app/'
    | '/_app/workspaces/$workspaceId/'
    | '/_app/workspaces/$workspaceId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_app/workspaces/$workspaceId/': {
      id: '/_app/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId/tasks/$taskId': {
      id: '/_app/workspaces/$workspaceId/tasks/$taskId'
      path: '/workspaces/$workspaceId/tasks/$taskId'
      fullPath: '/workspaces/$workspaceId/tasks/$taskId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspacesWorkspaceIdIndexRoute: typeof AppWorkspacesWorkspaceIdIndexRoute
  AppWorkspacesWorkspaceIdTasksTaskIdRoute: typeof AppWorkspacesWorkspaceIdTasksTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWorkspacesWorkspaceIdIndexRoute: AppWorkspacesWorkspaceIdIndexRoute,
  AppWorkspacesWorkspaceIdTasksTaskIdRoute:
    AppWorkspacesWorkspaceIdTasksTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSplatRoute: typeof SignUpSplatRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSplatRoute: SignUpSplatRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
